#!/bin/bash
mkdir -p ~/.vimbundles
cd ~/.vimbundles

get_bundle() {
  (
  if [ -d "$2" ]; then
    echo "Updating $1's $2"
    cd "$2"
    git pull --rebase
  else
    git clone "git://github.com/$1/$2.git"
  fi
  )
}

# get_bundle adamlowe vim-slurper # send stories to pivotal
get_bundle duff vim-bufonly         # close all buffers but current one/supplied one
get_bundle godlygeek tabular        # tabularize data based on supplied dilimiter (Tab /=)
get_bundle leshill vim-json         # syntax and highlighting for json text
get_bundle mileszs ack.vim          # run ack from vim
get_bundle pangloss vim-javascript  # syntax and highlighting for javascript
get_bundle scrooloose nerdcommenter # easier commenting
get_bundle tpope vim-abolish        # work with text abbreviations, substitution, and coercion
get_bundle tpope vim-bundler        # vim wrapper for some bundle commands
get_bundle tpope vim-endwise        # intelligently add endings to common ruby blocks/methods/classes/etc
get_bundle tpope vim-fugitive       # git wrapper
get_bundle tpope vim-git            # useful git syntax highlighting and text wrapping (for commits, etc)
get_bundle tpope vim-haml           # syntax and highlighting for haml
get_bundle tpope vim-markdown       # syntax and highlighting for markdown
get_bundle tpope vim-pathogen       # move all plugins to a central location and let pathogen load them
get_bundle tpope vim-ragtag         # xml/html mappings
# Gives eventual errors
# get_bundle tpope vim-rails          # common wrappings for rails
get_bundle tpope vim-repeat         # wrapts . operator in a way other plugins can use it
get_bundle tpope vim-speeddating
get_bundle tpope vim-surround
get_bundle tpope vim-unimpaired
get_bundle tpope vim-vividchalk
get_bundle vim-ruby vim-ruby
get_bundle wgibbs vim-irblack
get_bundle vim-scripts bufkill.vim
get_bundle jgdavey vim-blockle
get_bundle msanders snipmate.vim
get_bundle scrooloose nerdtree
get_bundle scrooloose syntastic
get_bundle ervandew supertab
get_bundle vim-scripts vimwiki
get_bundle garyharan vim-proto
get_bundle majutsushi tagbar        # add a tagbar to the left hand side to easily cycle through tags
get_bundle kien ctrlp.vim           # fuzzy finder
cd ~/.vim
if [ ! -d "autoload" ]; then
  mkdir "autoload"
fi

ln -sf $HOME/.vimbundles/vim-pathogen/autoload/pathogen.vim $HOME/.vim/autoload/pathogen.vim
vim -c 'call pathogen#helptags()|q'
